steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/alluz-backend:${_TAG}'
      - './backend'
images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/alluz-backend:${_TAG}'
substitutions:
  _REGION: 'us-central1'
  _REPO: 'alluz'
  _TAG: 'latest'
